name: Build and publish the LVE website

on:
  push:
    branches:
      - main


jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - name: Setup Fresh Virtual Environment
            run: |
              pip install --upgrade pip
              python3.10 -m venv env
              export PATH=$PATH:/home/docker/.local/bin
              source env/bin/activate
              echo "VIRTUAL ENV:" $VIRTUAL_ENV
          - name: Install Packaging Dependencies
            run: |
              pip install -e 'lve-tools[web]'
          - name: Build lve-tools/web/
            run: cd lve-tools/web && PYTHONPATH=../lve-tools/lve_tools python3 make.py
        
          - name: Deploy
            uses: s0/git-publish-subdir-action@develop
            env:
              REPO: self
              BRANCH: web
              FOLDER: lve-tools/web/build
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}